// Variables
#include "variables.h"

// Support functions
#include "addglitter.h"
#include "make_palettes.h"
#include "rings.h"

// Display routines
#include "circnoise_pal_1.h"
#include "circnoise_pal_1_ring.h"
#include "circnoise_pal_2.h"
#include "circnoise_pal_2_ring.h"
#include "circnoise_pal_3.h"
#include "circnoise_pal_3_ring.h"
#include "circnoise_pal_4.h"
#include "circnoise_pal_4_ring.h"
#include "confetti_pal.h"
#include "confetti_pal_ring.h"
#include "gradient_palettes.h"
#include "juggle_pal.h"
#include "juggle_pal_ring.h"
#include "matrix_pal.h"
#include "matrix_pal_ring.h"
#include "noise16_pal.h"
#include "noise8_pal.h"
#include "noise8_pal_ring.h"
#include "one_sin_pal.h"
#include "one_sin_pal_ring.h"
#include "rainbow_march.h"
#include "serendipitous_pal.h"
#include "serendipitous_pal_ring.h"
#include "three_sin_pal.h"
#include "three_sin_pal_ring.h"
#include "two_sin.h"
#include "two_sin_ring.h"
#include "loading_bar_pal.h"
