// Variables
#include "variables.h"

// Support functions
#include "addglitter.h"
//#include "checkDial.h"
#include "make_palettes.h"
#include "rings.h"

// Display routines
#include "circnoise.h"
#include "confetti_pal.h"
#include "discostrobe.h"
#include "fire.h"
#include "gradient_palettes.h"
#include "juggle_pal.h"
#include "matrix_pal.h"
//#include "noise16_pal.h"
#include "noise8_pal.h"
#include "one_sin_pal.h"
#include "palette_motion.h"
#include "plasma.h"
#include "pride.h"
#include "rainbow_march.h"
#include "ripple.h"
#include "serendipitous_pal.h"
#include "spiral.h"
#include "three_sin_pal.h"
#include "transition.h"
#include "twinkle.h"
#include "two_sin.h"
