// Variables
#include "variables.h"

// Support functions
//#include "addglitter.h"
//#include "checkDial.h"
#include "make_palettes.h"
#include "rings.h"

// Display routines
#include "circnoise.h"
//#include "confetti.h"
//#include "fire.h"
#include "gradient_palettes.h"
//#include "juggle.h"
//#include "matrix.h"
////#include "noise16_pal.h"
//#include "noise8.h"
//#include "one_sin.h"
//#include "palette_motion.h"
//#include "plasma.h"
//#include "pride.h"
//#include "rainbow_march.h"
//#include "ripple.h"
//#include "serendipitous.h"
//#include "spiral.h"
//#include "three_sin.h"
//#include "transition.h"
//#include "twinkle.h"
//#include "two_sin.h"
